name: classroom-autograde
on:
  push:
  workflow_dispatch:

jobs:
  autograde:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install soundfile pytest

      - name: Run evaluation
        run: |
          python evaluate.py --enroll tests/sample/enroll.wav --text tests/sample/prompt.txt --out out/out.wav
          echo "✅ Evaluation completed"
